version: 2

jobs:
  build:
    working_directory: ~/the-difference-engine/we-r-next-generation-web
    parallelism: 1
    shell: /bin/bash --login
    
    # Look at changing this imagehttps://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init

    steps:
      - checkout
      # This is based on your 1.0 configuration file or project settings
      - run:
          working_directory: ~/the-difference-engine/we-r-next-generation-web
          command: nvm install 8.9.4 && nvm alias default 8.9.4

      # Restore the dependency cache
      - restore_cache:
          keys:
          # Gets cache if package.json has not changed
          - v1-dep-{{ checksum "package.json" }}

      - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
      - run: export PATH="~/the-difference-engine/we-r-next-generation-web/node_modules/.bin:$PATH"
      
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Save dependency cache
      - save_cache:
          key: v1-dep-{{ checksum "package.json" }}
          paths:
              - node_modules

      # # Lint the source code
      # - run:
      #   name: Linting
      #   command: npm run lint

      # # Test the source code
      # - run:
      #   name: Testing
      #   command: npm run test

      # Build project
      - run:
          name: Building
          command: npm run build --config build/webpack.prod.conf.js

      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Branch }}-{{ .Revision }}
          paths:
              - dist

  deploy:
    working_directory: ~/the-difference-engine/we-r-next-generation-web
    docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
        # Restore cache from the build job which contains the
        # dist folder that needs to be deployed
        - restore_cache:
            key: v1-dist-{{ .Branch }}-{{ .Revision }}

        - run:
            name: Deploy to S3
            command: aws --region us-east-2 s3 sync dist s3://wrng --delete

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
